esphome:
  name: lilygo
  platformio_options:
    # Unless noted otherwise, based on https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/1eb6119fc31fcff7a6bafecb09f4225313859fc5/examples/demo/platformio.ini#L37
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    platform_packages:
      - "toolchain-riscv32-esp @8.4.0+2021r2-patch5"
    build_flags:  # the first three defines are required for the screen library to function.
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_RUNNING_CORE=0"  # TODO: this conflicts with the value from platformio's idedata, spewing a lot of warnings during the build.
      - "-DARDUINO_EVENT_RUNNING_CORE=0"  # and this too
      # In addition to lilygo's settings:
      # To enable reading logs over USB until `hardware_uart: USB_CDC` support
      # is added to `logger:`, as detailed in <https://github.com/esphome/feature-requests/issues/1906>:
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"


esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1

  framework:
    type: arduino
    # Just like in <https://community.home-assistant.io/t/enable-usb-cdc-to-log-hello-world-to-esp32-s3-dev-board-for-esphome/463164/10>
    # I had problems with newer versions; the following combination happens to work, so using it for now.
    version: 2.0.3
    platform_version: 5.1.1


logger:
  level: VERBOSE  # hardware_uart: USB_CDC  # see note about <https://github.com/esphome/feature-requests/issues/1906> above


api:  # Enable Home Assistant API
  password: !secret api_ota_password


ota:
  platform: esphome
  password: !secret api_ota_password


wifi: !include wifi-secrets.yaml


sensor:
  - platform: template
    name: "Dollar blue compra sensor"
    id: dollar_blue_compra
  - platform: template
    name: "Dollar blue Venta sensor"
    id: dollar_blue_venta

  - platform: template
    name: "Dollar mep compra sensor"
    id: dollar_mep_compra
  - platform: template
    name: "Dollar mep Venta sensor"
    id: dollar_mep_venta

  - platform: template
    name: "Dollar ccl compra sensor"
    id: dollar_ccl_compra
  - platform: template
    name: "Dollar ccl Venta sensor"
    id: dollar_ccl_venta

  - platform: template
    name: "Dollar cripto compra sensor"
    id: dollar_cripto_compra
  - platform: template
    name: "Dollar cripto Venta sensor"
    id: dollar_cripto_venta

  - platform: template
    name: "Days Until Next Holiday"
    id: days_until_holiday


text_sensor:
  - platform: template
    name: "Next Holiday Date"
    id: next_holiday_date
  - platform: template
    name: "Next Holiday Name"
    id: next_holiday_name
  - platform: template
    name: "Next Holiday Type"
    id: next_holiday_type



binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
    name: "Button 1"
    on_press:
      then:
        - display.page.show_next: eink_display
        - component.update: eink_display


interval:
  - interval: 60s
    then:
      - http_request.get:
          url: https://dolarapi.com/v1/dolares/blue
          capture_response: true
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d, Duration: %u ms, Text: %s"
                  args:
                    - response->status_code
                    - response->duration_ms
                    - body
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      id(dollar_blue_compra).publish_state(root["compra"]);
                      id(dollar_blue_venta).publish_state(root["venta"]);
                      return true;
                  });
      - http_request.get:
          url: https://dolarapi.com/v1/dolares/bolsa
          capture_response: true
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d, Duration: %u ms, Text: %s"
                  args:
                    - response->status_code
                    - response->duration_ms
                    - body
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      id(dollar_mep_compra).publish_state(root["compra"]);
                      id(dollar_mep_venta).publish_state(root["venta"]);
                      return true;
                  });
      - http_request.get:
          url: https://dolarapi.com/v1/dolares/contadoconliqui
          capture_response: true
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d, Duration: %u ms, Text: %s"
                  args:
                    - response->status_code
                    - response->duration_ms
                    - body
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      id(dollar_ccl_compra).publish_state(root["compra"]);
                      id(dollar_ccl_venta).publish_state(root["venta"]);
                      return true;
                  });
      - http_request.get:
          url: https://dolarapi.com/v1/dolares/cripto
          capture_response: true
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d, Duration: %u ms, Text: %s"
                  args:
                    - response->status_code
                    - response->duration_ms
                    - body
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      id(dollar_cripto_compra).publish_state(root["compra"]);
                      id(dollar_cripto_venta).publish_state(root["venta"]);
                      return true;
                  });
      - component.update: eink_display
  - interval: 25s
    then:
      - http_request.get:
          url: https://us-central1-arian-2g3d.cloudfunctions.net/next-holiday-api
          on_response:
            then:
              - logger.log:
                  format: "Holiday API: Response status: %d, Duration: %u ms, Text: %s, %s"
                  args:
                    - response->status_code
                    - response->duration_ms
                    - body
                    - body.c_str()
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                      id(days_until_holiday).publish_state(root["dias_hasta"]);
                      id(next_holiday_date).publish_state(root["fecha"]);
                      id(next_holiday_name).publish_state(root["nombre"]);
                      id(next_holiday_type).publish_state(root["tipo"]);
                      return true;
                  });
              - component.update: eink_display


external_components:
  source:
    type: local
    path: components/
  components: ["t547"]


font:
  - id: days_one
    file: "gfonts://Days+One"
    size: 50
    glyphs: "$!%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

  - id: roboto
    file: "gfonts://Roboto"
    size: 50
    glyphs: "$!%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

  - id: roboto_large
    file: "gfonts://Roboto"
    size: 90
    glyphs: "$!%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

  - id: roboto_small
    file: "gfonts://Roboto"
    size: 34
    glyphs: "$!%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

  - id: roboto_vsmall
    file: "gfonts://Roboto"
    size: 20
    glyphs: "$!%()+=,-_.:°/?0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"

  - id: material_trams
    file: "gfonts://Material+Icons"
    size: 50
    glyphs:
      - "\U0000E571" #tram
      - "\U0000E089" #arrow right
      - "\U0000E8DF" #calendar

  - id: material_large
    file: "gfonts://Material+Icons"
    size: 100
    glyphs:
      - "\U0000E8B5" #clock


time:
  - platform: sntp
    id: ntp


image:
  - file: "images/bg.png"
    id: bg
    resize: 540x960
  - file: "images/book.png"
    id: book_icon
    resize: 100x100
  - file: "images/caca.jpg"
    id: caca_icon
    resize: 250x250
  - file: "images/dollar.jpg"
    id: dollar_icon
    resize: 100x100
  - file: "images/dorayaki.jpg"
    id: img_dorayaki
    resize: 540x960
    type: GRAYSCALE
  - file: "images/screen_dolar.png"
    id: bg_dollar_screen
    resize: 540x960


http_request:
  id: dollar_rate_request
  timeout: 10s
  verify_ssl: false


display:
  - platform: t547
    id: eink_display
    rotation: 270
    update_interval: 600s
    pages:
      - id: next_holiday_page
        lambda: |-
          // Next Holiday
          int mid_screen_x = it.get_width()/2;
          it.printf(mid_screen_x, 720, id(roboto_small), COLOR_ON, TextAlign::TOP_CENTER, "Next Holiday: %s", id(next_holiday_name).state.c_str());
          it.printf(mid_screen_x, 760, id(roboto_small), COLOR_ON, TextAlign::TOP_CENTER, "Date: %s", id(next_holiday_date).state.c_str());
          it.printf(mid_screen_x, 800, id(roboto_small), COLOR_ON, TextAlign::TOP_CENTER, "Type: %s", id(next_holiday_type).state.c_str());
          it.printf(mid_screen_x, 840, id(roboto_small), COLOR_ON, TextAlign::TOP_CENTER, "In %d days", (int)id(days_until_holiday).state);

      - id: dollar_rate
        lambda: |-
          // Setup
          it.fill(COLOR_OFF);
          it.image(0,0, id(bg_dollar_screen));
          int mid_screen_x = it.get_width()/2;

          // Dollar blue
          it.printf(170, 360, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_blue_compra).state) ? "$%.0f" : "...",
                    id(dollar_blue_compra).state);
          it.printf(380, 360, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_blue_venta).state) ? "$%.0f" : "...",
                    id(dollar_blue_venta).state);

          // Dollar mep
          it.printf(170, 510, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_mep_compra).state) ? "$%.0f" : "...",
                    id(dollar_mep_compra).state);
          it.printf(380, 510, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_mep_venta).state) ? "$%.0f" : "...",
                    id(dollar_mep_venta).state);

          // Dollar ccl
          it.printf(170, 670, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_ccl_compra).state) ? "$%.0f" : "...",
                    id(dollar_ccl_compra).state);
          it.printf(380, 670, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_ccl_venta).state) ? "$%.0f" : "...",
                    id(dollar_ccl_venta).state);

          // Dollar cripto
          it.printf(170, 830, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_cripto_compra).state) ? "$%.0f" : "...",
                    id(dollar_cripto_compra).state);
          it.printf(380, 830, id(days_one), COLOR_ON, TextAlign::TOP_CENTER,
                    !isnan(id(dollar_cripto_venta).state) ? "$%.0f" : "...",
                    id(dollar_cripto_venta).state);
      - id: dorayaki
        lambda: |-
          // Setup
          it.fill(COLOR_OFF);
          it.image(0,0, id(img_dorayaki));

      - id: home
        lambda: |-
          // Setup
          it.fill(COLOR_OFF);
          it.image(0,0, id(bg));
          int mid_screen_x = it.get_width()/2;

          // Time & Date
          it.printf(mid_screen_x, 17, id(roboto_large), COLOR_ON, TextAlign::TOP_CENTER, id(ntp).now().strftime("%H:%M").c_str());
          it.printf(mid_screen_x, 120, id(roboto), COLOR_ON, TextAlign::TOP_CENTER, id(ntp).now().strftime("%Y-%m-%d").c_str());

          // Book icon
          int book_icon_w = 100;
          int book_start_x = 520/2 - book_icon_w/2;
          int book_start_y = 250;

          it.image(book_start_x, book_start_y, id(book_icon));

          // Book title
          it.printf(mid_screen_x, 315, id(roboto_small), COLOR_ON, TextAlign::TOP_CENTER, "El guardian entre el centeno");

          // Dollar  icon
          int dollar_icon_w = 100;
          int dollar_start_x = 50;
          int dollar_start_y = 460;

          it.image(dollar_start_x, dollar_start_y, id(dollar_icon));

          // Dollar Rate
          it.printf(200, 500, id(roboto_small), COLOR_ON, TextAlign::BASELINE_LEFT, "Venta: $%.0f", id(dollar_blue_venta).state);
          it.printf(200, 540, id(roboto_small), COLOR_ON, TextAlign::BASELINE_LEFT, "Compra: $%.0f", id(dollar_blue_compra).state);

          // Caca
          int caca_icon_w = 250;
          int caca_start_x = 520/2 - caca_icon_w/2;
          int caca_start_y = 650;

          it.image(caca_start_x, caca_start_y, id(caca_icon));

          // TODO: Agregar proximo feriado